name: ìê¸°ì†Œê°œ
run-name: ${{ github.actor }}ì˜ ìê¸°ì†Œê°œ í…ŒìŠ¤íŠ¸ ğŸš€
on:
  push:
    branches:
      - main
jobs:
  run-introduction:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: ìê¸°ì†Œê°œ ë¬¸êµ¬
        run: echo "ì½”ë”© ì´ˆë³´ì…ë‹ˆë‹¤. ìê¸°ì†Œê°œëŠ” ìƒëµí•©ë‹ˆë‹¤."